const Data = [
    { id:1,
      EmployeeName: "John Doe",
      Designation: "Manager",
      DC: "PIMCO",
      MobileNumber: "1234567890",
      Extension: "101",
      Location: "123 Main St",
      Email: "johndoe@example.com"
    },
    { id:2,
      EmployeeName: "Jane Smith",
      Designation: "Engineer",
      DC: "Sharemeister",
      MobileNumber: "9876543210",
      Extension: "202",
      Location: "456 Elm St",
      Email: "janesmith@example.com"
    },
    {
      id:3,  
      EmployeeName: "Michael Johnson",
      Designation: "Analyst",
      DC: "Tata Aig",
      MobileNumber: "5555555555",
      Extension: "303",
      Location: "789 Oak St",
      Email: "michaeljohnson@example.com"
    },
    {
        id:4,
      EmployeeName: "Emily Davis",
      Designation: "Designer",
      DC: "Accounts",
      MobileNumber: "9999999999",
      Extension: "404",
      Location: "321 Pine St",
      Email: "emilydavis@example.com"
    },
    { id:5,
      EmployeeName: "David Rodriguez",
      Designation: "Developer",
      DC: "Admin",
      MobileNumber: "1111111111",
      Extension: "505",
      Location: "654 Cedar St",
      Email: "davidrodriguez@example.com"
    },
    {id:6,
      EmployeeName: "Sarah Wilson",
      Designation: "Manager",
      DC: "AFLI",
      MobileNumber: "2222222222",
      Extension: "606",
      Location: "987 Maple St",
      Email: "sarahwilson@example.com"
    },
    { id:7,
      EmployeeName: "Christopher Taylor",
      Designation: "Engineer",
      DC: "Beacon Devops",
      MobileNumber: "3333333333",
      Extension: "707",
      Location: "159 Walnut St",
      Email: "christophertaylor@example.com"
    },
    {  id:8,
      EmployeeName: "Jessica Garcia",
      Designation: "Analyst",
      DC: "DPLI/PLIL",
      MobileNumber: "4444444444",
      Extension: "808",
      Location: "753 Birch St",
      Email: "jessicagarcia@example.com"
    },
    { id:9,
      EmployeeName: "Daniel Martinez",
      Designation: "Designer",
      DC: "Edward Jones",
      MobileNumber: "6666666666",
      Extension: "909",
      Location: "852 Spruce St",
      Email: "danielmartinez@example.com"
    },
    { id:10,
      EmployeeName: "Ashley Anderson",
      Designation: "Developer",
      DC: "Harton",
      MobileNumber: "7777777777",
      Extension: "010",
      Location: "951 Oak St",
      Email: "ashleyanderson@example.com"
    },
    { id:11,
      EmployeeName: "Matthew Thomas",
      Designation: "Manager",
      DC: "Human Resource",
      MobileNumber: "8888888888",
      Extension: "111",
      Location: "258 Elm St",
      Email: "matthewthomas@example.com"
    },
    { id:12,
      EmployeeName: "Amanda Hernandez",
      Designation: "Engineer",
      DC: "PIMCO",
      MobileNumber: "1212121212",
      Extension: "212",
      Location: "753 Pine St",
      Email: "amandahernandez@example.com"
    },
    { id:13,
      EmployeeName: "Andrew Walker",
      Designation: "Analyst",
      DC: "Tata Aig",
      MobileNumber: "1313131313",
      Extension: "313",
      Location: "456 Oak St",
      Email: "andrewwalker@example.com"
    },
    { id:14,
      EmployeeName: "Nicole Perez",
      Designation: "Designer",
      DC: "Human Resource",
      MobileNumber: "1414141414",
      Extension: "414",
      Location: "159 Cedar St",
      Email: "nicoleperez@example.com"
    },
    { id:15,
      EmployeeName: "Benjamin Turner",
      Designation: "Developer",
      DC: "Edward Jones",
      MobileNumber: "1515151515",
      Extension: "515",
      Location: "852 Maple St",
      Email: "benjaminturner@example.com"
    },
    { id:16,
      EmployeeName: "Samantha Cooper",
      Designation: "Manager",
      DC: "Beacon Devops",
      MobileNumber: "1616161616",
      Extension: "616",
      Location: "951 Walnut St",
      Email: "samanthacooper@example.com"
    },
    { id:17,
      EmployeeName: "Tyler Morgan",
      Designation: "Engineer",
      DC: "PIMCO",
      MobileNumber: "1717171717",
      Extension: "717",
      Location: "258 Pine St",
      Email: "tylermorgan@example.com"
    },
    { id:18,
      EmployeeName : "Olivia Reed",
      Designation : "Analyst",
      DC : "Sharemeister",
      MobileNumber: "1818181818",
      Extension: "818",
      Location: "753 Cedar St",
      Email: "oliviareed@example.com"
    },
    { id:19,
      EmployeeName: "Ethan Cook",
      Designation: "Designer",
      DC: "Tata Aig",
      MobileNumber: "1919191919",
      Extension: "919",
      Location: "456 Maple St",
      Email: "ethancook@example.com"
    }
  ];
  export default Data;